# Generated by Django 2.2.10 on 2020-06-29 14:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ponderation', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('mail', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='BE')),
                ('dateInscription', models.DateField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('periode', models.CharField(max_length=50)),
                ('start_Date', models.DateField()),
                ('end_Date', models.DateField()),
                ('status', models.BooleanField()),
                ('contry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Family_Tie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave_Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('starter', models.CharField(max_length=100)),
                ('main', models.CharField(max_length=100)),
                ('dessert', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=70)),
                ('mother_tong', models.CharField(max_length=50)),
                ('street_number', models.CharField(max_length=100)),
                ('ZIP_code', models.IntegerField()),
                ('city', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('Telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='BE')),
                ('dateInscription', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateNow', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('years', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libel', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('years', models.IntegerField()),
                ('street', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=50)),
                ('cp', models.IntegerField()),
                ('matricul', models.IntegerField()),
                ('status', models.BooleanField()),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Event')),
                ('id_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Meal')),
                ('id_rules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Rules')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section_year', models.IntegerField()),
                ('trimestrial', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=3)),
                ('nationality', models.CharField(max_length=70)),
                ('mother_tong', models.CharField(max_length=50)),
                ('hot_meal', models.BooleanField(default=False)),
                ('output_School', models.BooleanField(default=False)),
                ('agreement_image', models.BooleanField(default=False)),
                ('educational_agreement', models.BooleanField(default=False)),
                ('presence', models.BooleanField(default=False)),
                ('id_School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.SchoolPg')),
                ('id_inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Inscription')),
                ('id_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Level')),
                ('id_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='School_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.SchoolPg')),
                ('id_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room_number', models.IntegerField()),
                ('place_number', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('id_room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Room_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestrial', models.IntegerField()),
                ('id_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Level')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Professor_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_School_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.School_year')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Course')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Employee')),
                ('id_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Report')),
            ],
        ),
        migrations.CreateModel(
            name='Professor_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Course')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Parent_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_family_tie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Family_Tie')),
                ('id_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Parent')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Student')),
            ],
        ),
        migrations.CreateModel(
            name='MealMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Meal')),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='id_School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.SchoolPg'),
        ),
        migrations.AddField(
            model_name='meal',
            name='id_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Menu'),
        ),
        migrations.AddField(
            model_name='level',
            name='id_School_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.School_year'),
        ),
        migrations.AddField(
            model_name='level',
            name='id_classdiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.ClassDiary'),
        ),
        migrations.AddField(
            model_name='level',
            name='id_inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Inscription'),
        ),
        migrations.AddField(
            model_name='level',
            name='id_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Section'),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intituled', models.CharField(max_length=150)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('document', models.FileField(upload_to='')),
                ('id_leave_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Leave_Categorie')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='id_School_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.School_year'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.SchoolPg'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Grade'),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comportement', models.TextField()),
                ('home_work', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('id_classdiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.ClassDiary')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='classdiary',
            name='id_Schoolyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.School_year'),
        ),
        migrations.AddField(
            model_name='classdiary',
            name='id_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Level'),
        ),
        migrations.AddField(
            model_name='classdiary',
            name='id_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Student'),
        ),
        migrations.CreateModel(
            name='Class_room_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Room')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Employee')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Student')),
            ],
        ),
    ]
