# Generated by Django 2.2.16 on 2020-09-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School_Models', '0002_auto_20200903_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='id_classdiary',
        ),
    ]
