# Generated by Django 2.2.16 on 2020-09-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_Models', '0004_absence_messageabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='id_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='School_Models.Section'),
        ),
        migrations.AddField(
            model_name='event',
            name='Eventmessage',
            field=models.TextField(null=True),
        ),
    ]
