# Generated by Django 2.2.16 on 2020-09-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_Models', '0005_auto_20200920_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='School_Models.Section'),
        ),
    ]
