# Generated by Django 2.2.16 on 2020-09-24 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_Models', '0006_employee_id_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='communication',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='id_classdiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.ClassDiary', verbose_name='Journal de classe de '),
        ),
    ]
