# Generated by Django 2.2.16 on 2020-09-24 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_Models', '0007_auto_20200924_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagesBody', models.TextField()),
                ('msg_time', models.DateTimeField(auto_now=True)),
                ('id_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Parent')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Models.Employee')),
            ],
        ),
    ]
