# Generated by Django 2.2.16 on 2020-09-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_Models', '0008_messagesend'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
