# Generated by Django 2.2.10 on 2020-03-06 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('periode', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.BooleanField()),
                ('contry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('starter', models.CharField(max_length=100)),
                ('main', models.CharField(max_length=100)),
                ('dessert', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('years', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('years', models.IntegerField()),
                ('street', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=50)),
                ('cp', models.IntegerField()),
                ('matricule', models.IntegerField()),
                ('status', models.BooleanField()),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.Event')),
                ('id_repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.Food')),
                ('id_rules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.Rules')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='id_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.Menu'),
        ),
    ]
